foos/urls.py
from django.conf.urls import url

from . import views

app_name = 'foos'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^game/new/$', views.new_game, name='new_game'),
    url(r'^player/(?P<player_id>[0-9]+)/$', views.player, name='player'),
]

tabletracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('foos.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('registration.urls')),
    url(r'^accounts/login/', auth_views.login),
    url('^', include('django.contrib.auth.urls')),
]

foos/models.py
import datetime

from dateutil import tz
from django.db import models


class Player(models.Model):
    name = models.CharField(max_length=100)
    singles_wins = models.IntegerField(default=0)
    singles_losses = models.IntegerField(default=0)
    singles_draws = models.IntegerField(default=0)
    singles_games_played = models.IntegerField(default=0)
    doubles_wins = models.IntegerField(default=0)
    doubles_losses = models.IntegerField(default=0)
    doubles_draws = models.IntegerField(default=0)
    doubles_games_played = models.IntegerField(default=0)
    rating = models.IntegerField(default=1000)

    def __str__(self):
        return "%s" % (self.name)


class SinglesGame(models.Model):
    player1 = models.ForeignKey(Player, related_name='singles_team1', on_delete=models.CASCADE)
    player2 = models.ForeignKey(Player, related_name='singles_team2', on_delete=models.CASCADE)
    player1_score = models.IntegerField(default=0)
    player2_score = models.IntegerField(default=0)
    player1_start_rating = models.IntegerField(default=1000)
    player2_start_rating = models.IntegerField(default=1000)
    player1_end_rating = models.IntegerField(default=1000)
    player2_end_rating = models.IntegerField(default=1000)
    date = models.DateTimeField(default=datetime.datetime.now,
                                blank=True)

    def get_winner(self):
        if self.player1_score > self.player2_score:
            return self.player1
        else:
            return self.player2

    @property
    def get_date_string(self):
        desired_tz = tz.gettz('EST')
        modified_time = self.date.astimezone(desired_tz)
        return modified_time.strftime('%m/%d %I:%M %p')

    def __str__(self):
        return "%s vs. %s" % (self.player1,
                              self.player2)


class Team(models.Model):
    player1 = models.ForeignKey(Player, related_name='team_player1', on_delete=models.CASCADE)
    player2 = models.ForeignKey(Player, related_name='team_player2', on_delete=models.CASCADE)
    wins = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    games_played = models.IntegerField(default=0)
    rating = models.IntegerField(default=1000)

    def __str__(self):
        return "%s, %s" % (self.player1.name,
                           self.player2.name)


class DoublesGame(models.Model):
    team1 = models.ForeignKey(Team, related_name='doubles_team1', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Team, related_name='doubles_team2', on_delete=models.CASCADE)
    team1_score = models.IntegerField(default=0)
    team2_score = models.IntegerField(default=0)
    team1_start_rating = models.IntegerField(default=1000)
    team2_start_rating = models.IntegerField(default=1000)
    team1_end_rating = models.IntegerField(default=1000)
    team2_end_rating = models.IntegerField(default=1000)
    date = models.DateTimeField(default=datetime.datetime.now,
                                blank=True)

    @property
    def get_date_string(self):
        desired_tz = tz.gettz('EST')
        modified_time = self.date.astimezone(desired_tz)
        return modified_time.strftime('%m/%d %I:%M %p')

    def _str__(self):
        return "%s vs. %s" % (self.team1, self.team2)

foos/views.py
import math

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import SinglesGame, Player, DoublesGame, Team


@login_required
def index(request):
    recent_singles_games = SinglesGame.objects.order_by('-date')[:10]
    singles_ranking = Player.objects\
        .filter(singles_games_played__gte=4)\
        .order_by('-rating')

    processed_singles_games = []
    for game in recent_singles_games:
        setattr(game, 'player1_rating_change',
                game.player1_end_rating - game.player1_start_rating)
        setattr(game, 'player2_rating_change',
                game.player2_end_rating - game.player2_start_rating)
        processed_singles_games.append(game)

    recent_doubles_games = DoublesGame.objects.order_by('-date')[:10]
    doubles_ranking = Team.objects.order_by('-rating')

    processed_doubles_games = []
    for game in recent_doubles_games:
        setattr(game, 'team1_rating_change',
                game.team1_end_rating - game.team1_start_rating)
        setattr(game, 'team2_rating_change',
                game.team2_end_rating - game.team2_start_rating)
        processed_doubles_games.append(game)

    return render(request, 'foos/index.html', {
        'recent_singles_games' : processed_singles_games,
        'singles_ranking' : singles_ranking,
        'recent_doubles_games' : processed_doubles_games,
        'doubles_ranking' : doubles_ranking,
        'user' : request.user,
    }, content_type='application/xhtml+xml')


@login_required
def new_game(request):
    players = Player.objects.all().order_by('name')
    teams = Team.objects.all()
    # If it isn't a post, we are just going to display the game entry form
    if request.method != 'POST':
        return render(request, 'foos/game.html', {
            'players' : players,
            'teams' : teams,
        })

    else:
        try:
            game_type = request.POST['game_type']
        except KeyError:
            return render(request, 'foos/game.html', {
                'error_message' : 'Invalid POST received! Clown.',
                'players' : players,
                'teams' : teams,
            })

        # Singles game entry
        result = None
        if game_type == "singles":
            result = _validate_and_submit_singles_post(request)
        elif game_type == "doubles":
            result = _validate_and_submit_doubles_post(request)
        else:
            return render(request, 'foos/game.html', {
                'error_message' : 'Invalid game_type received! Clown.',
                'players' : players,
                'teams' : teams,
            })

        if result:
            if result['error']:
                return render(request, 'foos/game.html', {
                    'error_message' : result['error_message'],
                    'players' : players,
                    'teams' : teams,
                })

        # Whew! Okay, the result looks valid.
        return redirect('foos:index')


@login_required
def player(request, player_id):
    player = get_object_or_404(Player, pk=player_id)
    # Pull a list of all games played by the player
    singles_games = SinglesGame.objects\
        .filter(Q(player1=player) | Q(player2=player))\
        .order_by('-date')
    processed_singles_games = []
    for game in singles_games:
        setattr(game, 'player1_rating_change',
                game.player1_end_rating - game.player1_start_rating)
        setattr(game, 'player2_rating_change',
                game.player2_end_rating - game.player2_start_rating)
        processed_singles_games.append(game)
    # Build a list of wins/losses vs. every other player
    prob_player_list = _calculate_player_win_probs(player_id)
    # Build probability of winning vs every other player
    return render(request, 'foos/player.html', {
        'player' : player,
        'singles_games' : processed_singles_games,
        'player_probabilities' : prob_player_list
    })


def _calculate_player_win_probs(player_id):
    player = Player.objects.get(id=player_id)
    other_players = Player.objects.exclude(id=player_id)
    results = []
    for other in other_players:
        # Calculate the wins and losses vs. each player
        wins = 0
        losses = 0
        singles1 = SinglesGame.objects.filter(player1=player, player2=other)
        for game in singles1:
            if game.player1_score > game.player2_score:
                wins += 1
            elif game.player2_score > game.player1_score:
                losses += 1
        singles2 = SinglesGame.objects.filter(player1=other, player2=player)
        for game in singles2:
            if game.player1_score > game.player2_score:
                losses += 1
            elif game.player2_score > game.player1_score:
                wins += 1

        # Now calculate the probability of victory based on the rating
        # compared to the other player
        rating_difference = player.rating - other.rating
        base_prob = 1 / (1 + math.pow(10, (rating_difference / 400)))
        probability = 1 - base_prob
        probability = round(probability * 100, 1)
        player_obj = {
            'name' : other.name,
            'probability' : probability,
            'rating' : other.rating,
            'id' : other.id,
            'wins' : wins,
            'losses' : losses,
        }
        results.append( player_obj )

    return results

def _validate_and_submit_singles_post(request):
    return_data = {
        'error' : False,
        'error_message' : '',
        'status_message' : '',
    }

    try:
        player1_id = request.POST['player1']
        player2_id = request.POST['player2']
        player1_score = request.POST['player1_score']
        player2_score = request.POST['player2_score']
    except KeyError:
        return_data['error_message'] = 'Invalid POST received! Clown.'
        return_data['error'] = True
        return return_data

    # Make sure the same player isn't selected
    if player1_id == player2_id:
        return_data['error_message'] = 'You selected the same player! Clown.'
        return_data['error'] = True
        return return_data

    if player1_score == '' or player1_score is None:
        player1_score = 0
    if player2_score == '' or player2_score is None:
        player2_score = 0
    try:
        player1_score = int(player1_score)
        player2_score = int(player2_score)
    except Exception:
        return_data['error_message'] = 'Player score must be an integer! Clown.'
        return_data['error'] = True
        return return_data
    try:
        player1_id = int(player1_id)
        player2_id = int(player2_id)
    except Exception:
        return_data['error_message'] = "Don't try to submit weird data! Clown."
        return_data['error'] = True
        return return_data

    player1 = Player.objects.get(id=player1_id)
    player2 = Player.objects.get(id=player2_id)

    if not player1 and not player2:
        return_data['error_message'] = "Players do not exist! Clown."
        return_data['error'] = True
        return return_data

    # Check the scores to make sure they are in the range of 0-11
    if player1_score < 0 or player1_score > 11:
        return_data['error_message'] = 'Player 1 score was outside the range of 0-11! Clown.'
        return_data['error'] = True
        return return_data
     # Check the scores to make sure they are in the range of 0-11
    if player2_score < 0 or player2_score > 11:
        return_data['error_message'] = 'Player 2 score was outside the range of 0-11! Clown.'
        return_data['error'] = True
        return return_data
    # House rules. If a tiebreaker (win by 2) happened, the winning score must be 11-9.
    if player1_score == 11 or player2_score == 11:
        if player1_score != 9 and player2_score != 9:
            return_data['error_message'] = 'If win-by-two (tiebreaker), the resulting score must be 11-9!'
            return_data['error'] = True
            return return_data
    # House rules, cannot win by 1.
    if player1_score == 10 or player2_score == 10:
        if player1_score == 9 or player2_score == 9:
            return_data['error_message'] = 'If win-by-two (tiebreaker), the resulting score must be 11-9!'
            return_data['error'] = True
            return return_data

    if player1_score != 10 and player2_score != 10 and player1_score != 11 and player2_score != 11:
        if player1_score - player2_score != 0:
            return_data['error_message'] = 'Surely somebody won the game?'
            return_data['error'] = True
            return return_data

    p1_end_rating = _calculate_elo(player1.rating, player2.rating, player1_score, player2_score)
    p2_end_rating = _calculate_elo(player2.rating, player1.rating, player2_score, player1_score)

    s = SinglesGame(
        player1=player1,
        player2=player2,
        player1_score=player1_score,
        player2_score=player2_score,
        player1_start_rating=player1.rating,
        player2_start_rating=player2.rating,
        player1_end_rating=p1_end_rating,
        player2_end_rating=p2_end_rating,
    )
    s.save()

    if player1_score > player2_score:
        player1.singles_wins += 1
        player2.singles_losses += 1
    elif player2_score > player1_score:
        player2.singles_wins += 1
        player1.singles_losses += 1
    else:
        player1.singles_draws += 1
        player2.singles_draws += 1

    player1.singles_games_played += 1
    player2.singles_games_played += 1

    # Update ratings
    player1.rating = p1_end_rating
    player2.rating = p2_end_rating
    player1.save()
    player2.save()

    return return_data


def _validate_and_submit_doubles_post(request):
    return_data = {
        'error' : False,
        'error_message' : '',

foos/templates/foos/game.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if status_message %}<p><strong>{{ status_message }}</strong></p>{% endif %}

{% if players %}

<div class="row">
  <div class="col-md-12">
    <a href="{% url 'foos:index' %}">Leaderboard</a>
  </div>
</div>
<div class="row">


</div>

<div class="row">
  <div class="col-md-6">
    <h2>New Singles Game</h2>
  </div>
</div>
<div class="row">
  <form action="{% url 'foos:new_game' %}" method="post" class="form-horizontal">
  {% csrf_token %}
    <div class="form-group">
      <label class="col-sm-2 control-label text-danger">Red Player:</label>
      <div class="col-sm-4">
        <select name="player1">
        {% for player in players %}
          <option value="{{ player.id }}">{{ player.name }}</option>
        {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Score:</label>
      <div class="col-sm-4">
        <input type="text" name="player1_score" />
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label text-primary">Blue Player:</label>
      <div class="col-sm-4">
        <select name="player2">
        {% for player in players %}
          <option value="{{ player.id }}">{{ player.name }}</option>
        {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Score:</label>
      <div class="col-sm-4">
        <input type="text" name="player2_score" />
      </div>
    </div>
  <input type="hidden" name="game_type" value="singles" />
  <input type="submit" value="Submit" />
  </form>
</div>

<div class="row">
  <div class="col-md-6">
    <h2>New Doubles Game</h2>
  </div>
</div>

<div class="row">
  <form action="{% url 'foos:new_game' %}" method="post" class="form-horizontal">
  {% csrf_token %}
    <div class="form-group">
      <label class="col-sm-2 control-label text-danger">Red Team:</label>
      <div class="col-sm-4">
        <select name="team1player1">
        {% for player in players %}
          <option value="{{ player.id }}">{{ player.name }}</option>
        {% endfor %}
        </select>
      </div>
      <div class="col-sm-4">
        <select name="team1player2">
        {% for player in players %}
          <option value="{{ player.id }}">{{ player.name }}</option>
        {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Score:</label>
      <div class="col-sm-4">
        <input type="text" name="team1_score" />
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label text-primary">Blue Team:</label>
      <div class="col-sm-4">
        <select name="team2player1">
        {% for player in players %}
          <option value="{{ player.id }}">{{ player.name }}</option>
        {% endfor %}
        </select>
      </div>
      <div class="col-sm-4">
        <select name="team2player2">
        {% for player in players %}
          <option value="{{ player.id }}">{{ player.name }}</option>
        {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Score:</label>
      <div class="col-sm-4">
        <input type="text" name="team2_score" />
      </div>
    </div>
  <input type="hidden" name="game_type" value="doubles" />
  <input type="submit" value="Submit" />
  </form>
</div>

{% endif %}

{% endblock %}

foos/templates/foos/index.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col-md-3">
    <a href="{% url 'foos:new_game' %}">Enter a match result</a>
  </div>
  <div class="col-md-3">
    Logged in as {{user}}. <a href="{% url 'logout' %}">Logout?</a>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
  <h2>Recent Singles Games</h2>
  {% if recent_singles_games %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Date</th>
        <th>Rating Change</th>
        <th>Red Player</th>
        <th>Score</th>
        <th>Score</th>
        <th>Blue Player</th>
        <th>Rating Change</th>
      </tr>
      </thead>
      <tbody>
    {% for game in recent_singles_games %}
      <tr>
        <td>{{game.get_date_string}}</td>
        {% if game.player1_rating_change > 0 %}
          <td class="success">
        {% else %}
          <td class="danger">
        {% endif %}
        {{game.player1_end_rating}} ({{game.player1_rating_change}})</td>
        <td><a href="{% url 'foos:player' game.player1.id %}">{{game.player1}}</a></td>
        <td>{{game.player1_score}}</td>
        <td>{{game.player2_score}}</td>
        <td><a href="{% url 'foos:player' game.player2.id %}">{{game.player2}}</a></td>
        {% if game.player2_rating_change > 0 %}
          <td class="success">
        {% else %}
          <td class="danger">
        {% endif %}
        {{game.player2_end_rating}} ({{game.player2_rating_change}})</td>
      </tr>
    {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="row">
      <div class="col-md-8">No games available.</div>
    </div>
  {% endif %}
  </div>
  <div class="col-md-4">
  <h2>Singles Rankings</h2>
    {% if singles_ranking %}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Player</th>
          <th>Rating</th>
          <th>Wins</th>
          <th>Losses</th>
        </tr>
        </thead>
        <tbody>
      {% for player in singles_ranking %}
        <tr>
            <td><a href="{% url 'foos:player' player.id %}">{{player.name}}</a></td>
            <td>{{player.rating}}</td>
            <td>{{player.singles_wins}}</td>
            <td>{{player.singles_losses}}</td>
        </tr>
      {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>
</div>

<div class="row">
  <div class="col-md-8">
  <h2>Recent Doubles Games</h2>
  {% if recent_doubles_games %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Date</th>
        <th>Rating Change</th>
        <th>Red Team</th>
        <th>Score</th>
        <th>Score</th>
        <th>Blue Team</th>
        <th>Rating Change</th>
      </tr>
      </thead>
      <tbody>
    {% for game in recent_doubles_games %}
      <tr>
        <td>{{game.get_date_string}}</td>
        {% if game.team1_rating_change > 0 %}
          <td class="success">
        {% else %}
          <td class="danger">
        {% endif %}
        {{game.team1_end_rating}} ({{game.team1_rating_change}})</td>
        <td>{{game.team1}}</td>
        <td>{{game.team1_score}}</td>
        <td>{{game.team2_score}}</td>
        <td>{{game.team2}}</td>
        {% if game.team2_rating_change > 0 %}
          <td class="success">
        {% else %}
          <td class="danger">
        {% endif %}
        {{game.team2_end_rating}} ({{game.team2_rating_change}})</td>
      </tr>
    {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="row">
      <div class="col-md-8">No games available.</div>
    </div>
  {% endif %}
  </div>
  <div class="col-md-4">
  <h2>Doubles Rankings</h2>
    {% if doubles_ranking %}
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Team</th>
          <th>Rating</th>
          <th>Wins</th>
          <th>Losses</th>
        </tr>
        </thead>
        <tbody>
      {% for team in doubles_ranking %}
        <tr>
            <td>{{team}}</td>
            <td>{{team.rating}}</td>
            <td>{{team.wins}}</td>
            <td>{{team.losses}}</td>
        </tr>
      {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>
</div>

{% endblock %}

foos/templates/foos/player.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col-md-2">
    <a href="{% url 'foos:index' %}">Leaderboard</a>
  </div>
  <div class="col-md-2">
    <a href="{% url 'foos:new_game' %}">Enter a match result</a>
  </div>
  <div class="col-md-3">
    Logged in as {{user}}. <a href="{% url 'logout' %}">Logout?</a>
  </div>
</div>

<h1>{{player.name}} - Rating: {{player.rating}}</h1>

<div class="row">
  <div class="col-md-8">
    <h2>Singles Games</h2>
    {% if singles_games %}
      <table class="table table-striped">
      <thead>
      <tr>
        <th>Date</th>
        <th>Rating Change</th>
        <th>Red Player</th>
        <th>Score</th>
        <th>Score</th>
        <th>Blue Player</th>
        <th>Rating Change</th>
      </tr>
      </thead>
      <tbody>
    {% for game in singles_games %}
      <tr>
        <td>{{game.get_date_string}}</td>
        {% if game.player1_rating_change > 0 %}
          <td class="success">
        {% else %}
          <td class="danger">
        {% endif %}
        {{game.player1_end_rating}} ({{game.player1_rating_change}})</td>
        <td><a href="{% url 'foos:player' game.player1.id %}">{{game.player1}}</a></td>
        <td>{{game.player1_score}}</td>
        <td>{{game.player2_score}}</td>
        <td><a href="{% url 'foos:player' game.player2.id %}">{{game.player2}}</a></td>
        {% if game.player2_rating_change > 0 %}
          <td class="success">
        {% else %}
          <td class="danger">
        {% endif %}
        {{game.player2_end_rating}} ({{game.player2_rating_change}})</td>
      </tr>
    {% endfor %}
      </tbody>
    </table>
    {% else %}
      <div class="row">
        <div class="col-md-8">No games available.</div>
      </div>
    {% endif %}
  </div>
  <div class="col-md-4">
    <h2>Probability vs. Others</h2>
    {% if player_probabilities %}
      <table class="table table-striped">
      <thead>
      <tr>
        <th>Player</th>
        <th>Probability</th>
        <th>Wins</th>
        <th>Losses</th>
      </tr>
      </thead>
      <tbody>
      {% for player in player_probabilities %}
        <tr>
          <td><a href="{% url 'foos:player' player.id %}">{{player.name}}</a> ({{player.rating}})</td>
          <td>{{player.probability}}</td>
          <td>{{player.wins}}</td>
          <td>{{player.losses}}</td>
        </tr>
      {% endfor %}
      </tbody>
      </table>
    {% endif %}
  </div>
</div>

{% endblock %}